services:
  frontend:
    image: nginx
    ports: 
      - 3001:80
    volumes:
      - ./fe:/usr/share/nginx/html

  microservice:
    build: 
      context: ./webservice
    volumes: 
      - ./webservice:/app
    ports:
      - "3000:3000"
    expose:
      - 3000
